"use client";
import Image from"next/image";import Link from"@/components/app-link";import{ChangeEvent,FormEvent,useEffect,useState}from"react";import{createClient}from"@/lib/supabase/client";
type Relationship="self"|"child"|"dependent";type Visibility=Record<string,boolean>;
type Profile={id:string;user_id:string;status:"draft"|"published"|"hidden";subject_relationship:Relationship;responsibility_confirmed_at:string|null;preferred_name:string|null;birth_date:string|null;pronouns:string|null;blood_type:string|null;allergies:string|null;conditions:string|null;medications:string|null;support_needs:string|null;medical_devices:string|null;transfusion_preference:string|null;resuscitation_preference:string|null;organ_donor_status:string;organ_donor_notes:string|null;preferred_language:string|null;health_plan_name:string|null;other_guidance:string|null;photo_path:string|null;visibility:Visibility;updated_at:string};
type Product={product_id:string;emergency_profile_id:string|null;public_code:string;status:"active"|"blocked"|"revoked";activated_at:string};type Contact={id:string;user_id:string;emergency_profile_id:string;name:string;relationship:string|null;phone:string;is_public:boolean;sort_order:number};type Consent={id:string;emergency_profile_id:string|null;event_type:string;document_version:string;created_at:string;revoked_at:string|null};
type PanelSection="profile"|"contacts"|"products"|"consents";
const textFields=[
 ["preferred_name","Nome preferido",80,"Como a pessoa deve ser chamada"],["pronouns","Pronomes",40,"Ex.: ela/dela"],["allergies","Alergias",1000,"Medicamentos, alimentos, materiais e reações relevantes"],["conditions","Condições médicas",2000,"Somente condições importantes numa emergência"],["medications","Medicamentos de uso contínuo",2000,"Nome, dose e frequência, se desejar"],["support_needs","Necessidades de apoio",1000,"Comunicação, mobilidade ou outras necessidades"],["medical_devices","Dispositivos médicos",1000,"Marca-passo, sensor, prótese ou equipamento"],["transfusion_preference","Preferência sobre transfusão",300,"Declaração pessoal; não substitui documento médico"],["resuscitation_preference","Preferência sobre reanimação",300,"Declaração pessoal; não constitui diretiva válida"],["health_plan_name","Operadora do plano",100,"Somente o nome da operadora"],["other_guidance","Outras orientações",1500,"Informação curta e útil para quem estiver ajudando"],
]as const;
const fieldSections=[
 {title:"Identificação",description:"Dados básicos para reconhecer a pessoa.",keys:["preferred_name","pronouns"]},
 {title:"Saúde essencial",description:"Informações mais importantes durante um atendimento.",keys:["allergies","conditions","medications"]},
 {title:"Apoio e cuidados",description:"Necessidades, dispositivos e informações do plano.",keys:["support_needs","medical_devices","health_plan_name"]},
 {title:"Preferências e orientações",description:"Declarações pessoais e instruções complementares.",keys:["transfusion_preference","resuscitation_preference","other_guidance"]},
]as const;
const relationshipLabel:Record<Relationship,string>={self:"Meu perfil",child:"Filho(a)",dependent:"Dependente"};
const defaultVisibility:Visibility={photo:true,preferred_name:true,pronouns:true,age:true,blood_type:true,allergies:true,conditions:true,medications:true,support_needs:true,medical_devices:true,transfusion_preference:true,resuscitation_preference:true,organ_donor_status:true,preferred_language:true,health_plan_name:true,other_guidance:true,contacts:true};
const emptyProfile=(userId:string,relationship:Relationship,name:string):Partial<Profile>=>({user_id:userId,subject_relationship:relationship,responsibility_confirmed_at:relationship==="self"?null:new Date().toISOString(),preferred_name:name||null,visibility:{...defaultVisibility},organ_donor_status:"not_declared"});
function clean(value:unknown){return typeof value==="string"&&value.trim()?value.trim():null}
export default function PainelClient({userId,initialProfiles,initialProducts,initialContacts,initialConsents,initialPhotoUrls}:{userId:string;initialProfiles:Profile[];initialProducts:Product[];initialContacts:Contact[];initialConsents:Consent[];initialPhotoUrls:Record<string,string>}){
 const[profiles,setProfiles]=useState(initialProfiles);const[selectedId,setSelectedId]=useState(initialProfiles[0]?.id??"");const[products,setProducts]=useState(initialProducts);const[contacts,setContacts]=useState(initialContacts);const[consents]=useState(initialConsents);const[photoUrls,setPhotoUrls]=useState(initialPhotoUrls);const[dirty,setDirty]=useState(false);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[creating,setCreating]=useState(false);const[confirmSensitive,setConfirmSensitive]=useState(false);const[confirmPublication,setConfirmPublication]=useState(false);const[openSections,setOpenSections]=useState(()=>new Set([0,1]));const[panelSection,setPanelSection]=useState<PanelSection>("profile");
 const profile=profiles.find(item=>item.id===selectedId)??null;const profileProducts=products.filter(item=>item.emergency_profile_id===selectedId);const profileContacts=contacts.filter(item=>item.emergency_profile_id===selectedId).sort((a,b)=>a.sort_order-b.sort_order);const profileConsents=consents.filter(item=>item.emergency_profile_id===selectedId);
 useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler)},[dirty]);
 function change(key:keyof Profile,value:unknown){if(!profile)return;setProfiles(list=>list.map(item=>item.id===profile.id?{...item,[key]:value}:item));setDirty(true);setMessage("")}
 function toggle(key:string){if(!profile)return;change("visibility",{...profile.visibility,[key]:!profile.visibility?.[key]})}
 async function createProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const relationship=String(data.get("relationship"))as Relationship;const name=String(data.get("name")||"").trim();if(!name)return setMessage("Informe o nome preferido do perfil.");setSaving(true);const{data:created,error}=await createClient().from("emergency_profiles").insert(emptyProfile(userId,relationship,name)).select("*").single();setSaving(false);if(error||!created)return setMessage(relationship==="self"?"Já existe um perfil próprio ou não foi possível criar o perfil.":"Não foi possível criar o perfil.");setProfiles(list=>[created as Profile,...list]);setSelectedId(created.id);setCreating(false);setMessage("Perfil criado em modo privado.")}
 async function save(){if(!profile)return;setSaving(true);setMessage("");const payload={preferred_name:clean(profile.preferred_name),birth_date:profile.birth_date||null,pronouns:clean(profile.pronouns),blood_type:profile.blood_type||null,allergies:clean(profile.allergies),conditions:clean(profile.conditions),medications:clean(profile.medications),support_needs:clean(profile.support_needs),medical_devices:clean(profile.medical_devices),transfusion_preference:clean(profile.transfusion_preference),resuscitation_preference:clean(profile.resuscitation_preference),organ_donor_status:profile.organ_donor_status||"not_declared",organ_donor_notes:clean(profile.organ_donor_notes),preferred_language:clean(profile.preferred_language),health_plan_name:clean(profile.health_plan_name),other_guidance:clean(profile.other_guidance),visibility:profile.visibility,updated_at:new Date().toISOString()};const{data,error}=await createClient().from("emergency_profiles").update(payload).eq("id",profile.id).select("*").single();setSaving(false);if(error||!data)return setMessage("Não foi possível salvar. Revise os campos e tente novamente.");setProfiles(list=>list.map(item=>item.id===profile.id?data as Profile:item));setDirty(false);setMessage("Alterações salvas com segurança.")}
 async function publish(){if(!profile||dirty)return setMessage("Salve as alterações antes de publicar.");if(!hasActiveProduct)return setMessage(hasAccountActiveProduct?"O chaveiro ativo está vinculado a outro perfil. Selecione o perfil usado na ativação.":"Ative um chaveiro para este perfil antes de publicar.");if(!hasPublicName)return setMessage("Marque o nome preferido como público antes de publicar.");if(!hasUsefulPublicInfo)return setMessage("Marque ao menos uma informação útil preenchida como pública, como alergias, condições, medicamentos, apoio, dispositivo ou contato.");if(!confirmSensitive||!confirmPublication)return setMessage("Confirme os dois consentimentos antes de publicar.");setSaving(true);const{data,error}=await createClient().rpc("server_publish_emergency_profile",{p_profile_id:profile.id,p_sensitive_version:"sensitive-v1",p_publication_version:"publication-v1"});setSaving(false);if(error||!data)return setMessage("Não foi possível concluir a publicação. Atualize a página e tente novamente.");setProfiles(list=>list.map(item=>item.id===profile.id?{...item,status:"published",published_at:new Date().toISOString()}:item));setMessage("Perfil publicado. Os campos selecionados já podem ser consultados.")}
 async function hide(){if(!profile)return;setSaving(true);const{data,error}=await createClient().rpc("server_hide_emergency_profile",{p_profile_id:profile.id});setSaving(false);if(error||!data)return setMessage("Não foi possível ocultar o perfil.");setProfiles(list=>list.map(item=>item.id===profile.id?{...item,status:"hidden"}:item));setMessage("Perfil ocultado imediatamente.")}
 async function uploadPhoto(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!profile||!file)return;if(file.size>5*1024*1024||!["image/jpeg","image/png","image/webp"].includes(file.type))return setMessage("Use JPEG, PNG ou WebP com até 5 MB.");setSaving(true);const extension=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${userId}/${profile.id}/${crypto.randomUUID()}.${extension}`;const supabase=createClient();const{error}=await supabase.storage.from("profile-photos").upload(path,file,{upsert:false,contentType:file.type,cacheControl:"60"});if(error){setSaving(false);return setMessage("Não foi possível enviar a foto.")}if(profile.photo_path)await supabase.storage.from("profile-photos").remove([profile.photo_path]);const{error:updateError}=await supabase.from("emergency_profiles").update({photo_path:path,updated_at:new Date().toISOString()}).eq("id",profile.id);const{data:signed}=await supabase.storage.from("profile-photos").createSignedUrl(path,900);setSaving(false);if(updateError)return setMessage("A foto foi enviada, mas não pôde ser vinculada ao perfil.");change("photo_path",path);setDirty(false);if(signed?.signedUrl)setPhotoUrls(urls=>({...urls,[profile.id]:signed.signedUrl}));setMessage("Foto atualizada.")}
 async function addContact(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!profile||profileContacts.length>=3)return;const form=event.currentTarget;const data=new FormData(form);const name=String(data.get("name")||"").trim();const relationship=String(data.get("relationship")||"").trim();const phone=String(data.get("phone")||"").replace(/[^+\d]/g,"");if(!name||!/^\+[1-9]\d{7,14}$/.test(phone))return setMessage("Informe nome e telefone internacional, por exemplo +5565999990000.");const{data:created,error}=await createClient().from("emergency_contacts").insert({user_id:userId,emergency_profile_id:profile.id,name,relationship:relationship||null,phone,is_public:true,sort_order:profileContacts.length}).select("*").single();if(error||!created)return setMessage("Não foi possível adicionar o contato.");setContacts(list=>[...list,created as Contact]);form.reset();setMessage("Contato adicionado como público. Você pode torná-lo privado quando quiser.")}
 async function updateContact(id:string,changes:Partial<Contact>){const{data,error}=await createClient().from("emergency_contacts").update(changes).eq("id",id).select("*").single();if(error||!data)return setMessage("Não foi possível atualizar o contato.");setContacts(list=>list.map(item=>item.id===id?data as Contact:item))}
 async function removeContact(id:string){const{error}=await createClient().from("emergency_contacts").delete().eq("id",id);if(error)return setMessage("Não foi possível remover o contato.");setContacts(list=>list.filter(item=>item.id!==id));setMessage("Contato removido.")}
 async function blockProduct(id:string){if(!confirm("Bloquear este produto por perda ou roubo? A consulta pública será interrompida imediatamente."))return;const{data,error}=await createClient().rpc("server_block_my_product",{p_product_id:id});if(error||!data)return setMessage("Não foi possível bloquear o produto.");setProducts(list=>list.map(item=>item.product_id===id?{...item,status:"blocked"}:item));setMessage("Produto bloqueado. O token NFC e o código não retornam o perfil.")}
 const publicKeys=profile?Object.entries(profile.visibility??{}).filter(([,value])=>value).map(([key])=>key):[];const hasActiveProduct=profileProducts.some(item=>item.status==="active");const hasAccountActiveProduct=products.some(item=>item.status==="active");const hasPublicName=Boolean(profile?.preferred_name&&profile.visibility.preferred_name);const hasUsefulPublicInfo=Boolean(profile&&[["allergies",profile.allergies],["conditions",profile.conditions],["medications",profile.medications],["support_needs",profile.support_needs],["medical_devices",profile.medical_devices]].some(([key,value])=>Boolean(value&&profile.visibility[key as string]))||(profile?.visibility.contacts&&profileContacts.some(contact=>contact.is_public)));
 return <main className="dashboard phase2"><aside><Link className="brand" href="/"><b>R</b>Resolveu<span>Lab</span></Link><nav><a className="active" href="/painel">◫ Perfis</a><a href="/seguranca">⚙ Segurança</a><a href="/conta">◎ Conta e privacidade</a></nav><small>Conta adulta responsável</small><form className="logoutForm" action="/auth/sair" method="post"><button className="logoutButton">Sair</button></form></aside><section><header><div><p className="kicker">PAINEL DA RESPONSÁVEL</p><h1>Perfis de emergência</h1></div><button className="primary" onClick={()=>setCreating(value=>!value)}>+ Novo perfil</button></header>
 {creating&&<form className="createProfile" onSubmit={createProfile}><label>Nome preferido<input name="name" maxLength={80} required/></label><label>Este perfil é de<select name="relationship" defaultValue="child"><option value="self">Mim</option><option value="child">Meu filho ou filha</option><option value="dependent">Outro dependente</option></select></label><label className="check"><input type="checkbox" required/> Declaro que sou responsável e tenho legitimidade para administrar estes dados.</label><button className="primary" disabled={saving}>Criar perfil privado</button></form>}
 <div className="profileTabs" role="tablist">{profiles.map(item=><button role="tab" aria-selected={item.id===selectedId} className={item.id===selectedId?"selected":""} key={item.id} onClick={()=>{if(!dirty||confirm("Descartar alterações não salvas?")){setSelectedId(item.id);setDirty(false);setMessage("")}}}><b>{item.preferred_name||"Sem nome"}</b><small>{relationshipLabel[item.subject_relationship]} • {item.status==="published"?"Publicado":item.status==="hidden"?"Oculto":"Rascunho"}</small></button>)}</div>
 {!profile?<article className="emptyPanel"><h2>Crie o primeiro perfil</h2><p>Você pode criar seu perfil, o de um filho ou de outro dependente. Tudo começa privado.</p></article>:<><div className="summary"><div><small>PERFIL</small><b>{profile.preferred_name||"Sem nome"} • {relationshipLabel[profile.subject_relationship]}</b></div><div><small>ÚLTIMA ATUALIZAÇÃO</small><b>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(profile.updated_at))}</b></div>{profile.status==="published"?<button className="danger" onClick={hide} disabled={saving}>Ocultar imediatamente</button>:<span className="hidden">● Perfil privado</span>}</div>
 <nav className="panelSections" aria-label="Seções do perfil">{[["profile","Informações"],["contacts",`Contatos (${profileContacts.length})`],["products",`Chaveiros (${profileProducts.length})`],["consents",`Consentimentos (${profileConsents.length})`]].map(([id,label])=><button type="button" key={id} className={panelSection===id?"active":""} aria-current={panelSection===id?"page":undefined} onClick={()=>setPanelSection(id as PanelSection)}>{label}</button>)}</nav>
 {panelSection==="profile"&&<div className="phase2Grid"><article className="editor"><h2>Informações do perfil</h2><p>Preencha por seções. Salvar não publica; cada controle define o que poderá aparecer.</p>
 {fieldSections.map((section,index)=><details className="profileSection" key={section.title} open={openSections.has(index)} onToggle={event=>{const isOpen=event.currentTarget.open;setOpenSections(current=>{const next=new Set(current);if(isOpen)next.add(index);else next.delete(index);return next})}}><summary><span><b>{section.title}</b><small>{section.description}</small></span><i aria-hidden="true">⌄</i></summary><div className="profileSectionBody">
  {index===0&&<><div className="photoEditor">{photoUrls[profile.id]?<Image unoptimized width={72} height={72} src={photoUrls[profile.id]} alt={`Foto de ${profile.preferred_name||"perfil"}`}/>:<div className="avatar">Foto</div>}<label className="secondary">Alterar foto<input type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadPhoto} hidden/></label><VisibilityToggle label="Foto pública" active={Boolean(profile.visibility.photo)} onClick={()=>toggle("photo")}/></div><div className="formColumns"><label>Data de nascimento<input type="date" max={new Date().toISOString().slice(0,10)} value={profile.birth_date??""} onChange={e=>change("birth_date",e.target.value||null)}/><VisibilityToggle label="Publicar somente a idade" active={Boolean(profile.visibility.age)} onClick={()=>toggle("age")}/></label><label>Idioma preferencial<input maxLength={40} value={profile.preferred_language??""} onChange={e=>change("preferred_language",e.target.value)}/><VisibilityToggle label="Público" active={Boolean(profile.visibility.preferred_language)} onClick={()=>toggle("preferred_language")}/></label></div></>}
  {index===1&&<div className="formColumns bloodField"><label>Tipo sanguíneo<select value={profile.blood_type??""} onChange={e=>change("blood_type",e.target.value||null)}><option value="">Não informado</option>{["A+","A-","B+","B-","AB+","AB-","O+","O-"].map(value=><option key={value}>{value}</option>)}</select><VisibilityToggle label="Público" active={Boolean(profile.visibility.blood_type)} onClick={()=>toggle("blood_type")}/></label></div>}
  {textFields.filter(([key])=>(section.keys as readonly string[]).includes(key)).map(([key,label,max,help])=><label className="profileField" key={key}>{label}<small>{help}</small>{max>100?<textarea maxLength={max} value={String(profile[key]??"")} onChange={e=>change(key,e.target.value)}/>:<input maxLength={max} value={String(profile[key]??"")} onChange={e=>change(key,e.target.value)}/>}<VisibilityToggle label="Público" active={Boolean(profile.visibility[key])} onClick={()=>toggle(key)}/></label>)}
  {index===3&&<label className="profileField">Doação de órgãos<select value={profile.organ_donor_status} onChange={e=>change("organ_donor_status",e.target.value)}><option value="not_declared">Não declarado</option><option value="yes">Declara ser doador(a)</option><option value="no">Declara não ser doador(a)</option><option value="unknown">Não sabe</option></select><input maxLength={300} placeholder="Observação opcional" value={profile.organ_donor_notes??""} onChange={e=>change("organ_donor_notes",e.target.value)}/><VisibilityToggle label="Publicar declaração e observação" active={Boolean(profile.visibility.organ_donor_status)} onClick={()=>toggle("organ_donor_status")}/></label>}
 </div></details>)}
 <button className="primary saveButton" onClick={save} disabled={saving||!dirty}>{saving?"Salvando…":dirty?"Salvar alterações":"Tudo salvo"}</button></article>
 <div className="rightRail"><article className="preview"><div><small>PRÉ-VISUALIZAÇÃO</small><Link href={`/preview?perfil=${encodeURIComponent(profile.id)}`}>Abrir prévia exata ↗</Link></div>{photoUrls[profile.id]&&profile.visibility.photo&&<Image unoptimized width={72} height={72} className="previewPhoto" src={photoUrls[profile.id]} alt=""/>}<h3>{profile.visibility.preferred_name?profile.preferred_name:"Nome privado"}</h3>{profile.visibility.allergies&&profile.allergies&&<div className="miniAlert"><small>ALERGIAS</small><b>{profile.allergies}</b></div>}<p><small>CAMPOS PÚBLICOS</small><b>{publicKeys.length?`${publicKeys.length} selecionados`:"Nenhum campo selecionado"}</b></p></article>
 <article className="publishCard"><h3>Publicação</h3><ul className="publishChecklist"><li className={hasActiveProduct?"ready":""}>{hasActiveProduct?"✓":"○"} Chaveiro ativo neste perfil</li><li className={hasPublicName?"ready":""}>{hasPublicName?"✓":"○"} Nome preferido público</li><li className={hasUsefulPublicInfo?"ready":""}>{hasUsefulPublicInfo?"✓":"○"} Informação útil pública</li></ul>{!hasActiveProduct&&hasAccountActiveProduct&&<p className="checkHint">Há um chaveiro ativo em outro perfil desta conta.</p>}<label className="check"><input type="checkbox" checked={confirmSensitive} onChange={e=>setConfirmSensitive(e.target.checked)}/> Autorizo o tratamento dos dados sensíveis deste perfil.</label><label className="check"><input type="checkbox" checked={confirmPublication} onChange={e=>setConfirmPublication(e.target.checked)}/> Entendo que os campos públicos poderão ser acessados por qualquer pessoa com o chaveiro ou código.</label><button className="primary" disabled={saving||profile.status==="published"} onClick={publish}>{profile.status==="published"?"Perfil publicado":"Publicar perfil"}</button></article></div></div>}
 {panelSection==="contacts"&&<section className="management sectionPanel" id="contatos"><header><div><p className="kicker">ATÉ 3 CONTATOS</p><h2>Contatos de emergência</h2></div><VisibilityToggle label="Mostrar contatos na página pública" active={Boolean(profile.visibility.contacts)} onClick={()=>toggle("contacts")}/></header>{profileContacts.map(contact=><div className="contactRow" key={contact.id}><span><b>{contact.name}</b><small>{contact.relationship} • {contact.phone}</small></span><VisibilityToggle label={contact.is_public?"Público":"Privado"} active={contact.is_public} onClick={()=>updateContact(contact.id,{is_public:!contact.is_public})}/><button onClick={()=>removeContact(contact.id)}>Remover</button></div>)}{profileContacts.length<3&&<form className="addContact" onSubmit={addContact}><input name="name" placeholder="Nome" maxLength={80} required/><input name="relationship" placeholder="Vínculo" maxLength={60}/><input name="phone" placeholder="+5565999990000" required/><button className="secondary">Adicionar contato</button></form>}</section>}
 {panelSection==="products"&&<section className="management sectionPanel" id="produtos"><p className="kicker">PRODUTOS VINCULADOS</p><h2>Chaveiros deste perfil</h2>{profileProducts.length?profileProducts.map(product=><div className="productRow" key={product.product_id}><span><b>{product.public_code}</b><small>{product.status==="active"?"Ativo":product.status==="blocked"?"Bloqueado":"Revogado"}</small></span>{product.status==="active"&&<button className="danger" onClick={()=>blockProduct(product.product_id)}>Informar perda ou roubo</button>}</div>):<p>Nenhum produto vinculado. <Link href="/ativar">Ativar um chaveiro para este perfil →</Link></p>}</section>}
 {panelSection==="consents"&&<section className="management sectionPanel" id="consentimentos"><p className="kicker">HISTÓRICO IMUTÁVEL</p><h2>Consentimentos</h2>{profileConsents.length?profileConsents.map(event=><div className="consentRow" key={event.id}><span><b>{event.event_type==="publication_authorization"?"Autorização de publicação":event.event_type==="sensitive_data_consent"?"Tratamento de dados sensíveis":"Publicação revogada"}</b><small>Versão {event.document_version}</small></span><time>{new Intl.DateTimeFormat("pt-BR").format(new Date(event.created_at))}</time></div>):<p>Nenhum consentimento registrado para este perfil.</p>}</section>}</>}{message&&<div className="toast" role="status">{message}</div>}</section></main>}
function VisibilityToggle({label,active,onClick}:{label:string;active:boolean;onClick:()=>void}){return <span className="visibilityControl"><button type="button" onClick={onClick} className={active?"toggle on":"toggle"} aria-pressed={active} aria-label={`${label}: ${active?"público":"privado"}`}><i/></button><em>{active?label:"Privado"}</em></span>}
