import{createClient}from"npm:@supabase/supabase-js@2.112.3";
const defaultOrigins=["http://localhost:3000","https://sos.resolveulab.com.br","https://sos.resolveuapp.com.br"];
const origins=[...new Set([...defaultOrigins,...(Deno.env.get("ALLOWED_ORIGINS")||"").split(",").map(value=>value.trim()).filter(Boolean)])];
function headers(req:Request){const origin=req.headers.get("origin")||"";return{"cache-control":"no-store","x-content-type-options":"nosniff","x-robots-tag":"noindex, nofollow, noarchive","referrer-policy":"no-referrer","access-control-allow-origin":origins.includes(origin)?origin:origins[0],"access-control-allow-headers":"authorization, x-client-info, apikey, content-type, x-retry-count, traceparent, tracestate, baggage","access-control-allow-methods":"POST, OPTIONS","vary":"origin","x-correlation-id":crypto.randomUUID()}}
function response(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...headers(req),"content-type":"application/json"}})}
function preflight(req:Request){return new Response(null,{status:204,headers:headers(req)})}
const encoder=new TextEncoder();const codePattern=/^[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{5}$/;const tokenPattern=/^[A-Za-z0-9_-]{22,256}$/;
async function digest(value:string){const bytes=await crypto.subtle.digest("SHA-256",encoder.encode(value));return`\\x${Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("")}`}
async function verifyCaptcha(token:string,ip:string){const secret=Deno.env.get("CAPTCHA_SECRET");if(!secret||!token||token.length>2048)return false;const form=new FormData();form.set("secret",secret);form.set("response",token);if(ip!=="unknown")form.set("remoteip",ip);const result=await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify",{method:"POST",body:form});if(!result.ok)return false;const body=await result.json();return body.success===true}
Deno.serve(async req=>{const started=Date.now();if(req.method==="OPTIONS")return preflight(req);if(req.method!=="POST")return response(req,{error:"Método não permitido"},405);try{const body=await req.json();const mode=body.mode==="nfc"?"nfc":"code";const code=typeof body.code==="string"?body.code.trim().toUpperCase():"";const token=typeof body.token==="string"?body.token:"";if((mode==="code"&&!codePattern.test(code))||(mode==="nfc"&&!tokenPattern.test(token)))throw new Error("invalid");const ip=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||req.headers.get("cf-connecting-ip")||"unknown";const secretKey=Deno.env.get("SUPABASE_SECRET_KEY")??Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");const url=Deno.env.get("SUPABASE_URL");if(!secretKey||!url)throw new Error("config");const captchaToken=typeof body.captchaToken==="string"?body.captchaToken:"";const captchaVerified=captchaToken?await verifyCaptcha(captchaToken,ip):false;const admin=createClient(url,secretKey,{auth:{persistSession:false,autoRefreshToken:false}});const{data,error}=await admin.rpc("server_get_emergency_profile",{p_code:mode==="code"?code:null,p_token_hash:mode==="nfc"?await digest(token):null,p_origin_hash:await digest(`${secretKey}:${ip}`),p_mode:mode,p_captcha_verified:captchaVerified});const profile=data&&typeof data==="object"?{...data}:data;if(profile?.photoPath){const{data:signed}=await admin.storage.from("profile-photos").createSignedUrl(profile.photoPath,60);delete profile.photoPath;if(signed?.signedUrl)profile.photoUrl=signed.signedUrl}const remaining=Math.max(0,300-(Date.now()-started));if(remaining)await new Promise(resolve=>setTimeout(resolve,remaining));if(error)return response(req,{profile:null});if(profile?.captcha_required)return response(req,{profile:null,captchaRequired:true});return response(req,{profile:profile||null})}catch{const remaining=Math.max(0,300-(Date.now()-started));if(remaining)await new Promise(resolve=>setTimeout(resolve,remaining));return response(req,{profile:null})}});
