create table private.emergency_lookup_attempts(id bigint generated always as identity primary key,origin_hash bytea not null check(octet_length(origin_hash)=32),lookup_mode text not null check(lookup_mode in('code','nfc')),succeeded boolean not null,outcome text not null check(outcome in('found','unavailable','captcha_required','rate_limited')),created_at timestamptz not null default now());
create index emergency_lookup_origin_recent_idx on private.emergency_lookup_attempts(origin_hash,lookup_mode,created_at desc);
revoke all on private.emergency_lookup_attempts from public,anon,authenticated;
create function public.server_get_emergency_profile(p_code text,p_token_hash bytea,p_origin_hash bytea,p_mode text,p_captcha_verified boolean default false) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_attempts integer;v_product private.products;v_profile public.emergency_profiles;v_result jsonb;v_contacts jsonb;
begin
 if p_origin_hash is null or octet_length(p_origin_hash)<>32 or p_mode not in('code','nfc') or(p_mode='code'and(p_code is null or p_code!~'^[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{5}$'))or(p_mode='nfc'and(p_token_hash is null or octet_length(p_token_hash)<>32))then return null;end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(encode(p_origin_hash,'hex')||p_mode,2));
 select count(*)into v_attempts from private.emergency_lookup_attempts where origin_hash=p_origin_hash and lookup_mode=p_mode and created_at>=now()-interval'10 minutes';
 if(p_mode='code'and v_attempts>=20)or(p_mode='nfc'and v_attempts>=60)then insert into private.emergency_lookup_attempts(origin_hash,lookup_mode,succeeded,outcome)values(p_origin_hash,p_mode,false,'rate_limited');return null;end if;
 if p_mode='code'and v_attempts>=3 and not p_captcha_verified then insert into private.emergency_lookup_attempts(origin_hash,lookup_mode,succeeded,outcome)values(p_origin_hash,p_mode,false,'captcha_required');return jsonb_build_object('captcha_required',true);end if;
 select*into v_product from private.products where status='active'and((p_mode='code'and public_code=p_code)or(p_mode='nfc'and nfc_token_hash=p_token_hash))limit 1;
 if not found then insert into private.emergency_lookup_attempts(origin_hash,lookup_mode,succeeded,outcome)values(p_origin_hash,p_mode,false,'unavailable');return null;end if;
 select*into v_profile from public.emergency_profiles where user_id=v_product.owner_id and status='published';
 if not found then insert into private.emergency_lookup_attempts(origin_hash,lookup_mode,succeeded,outcome)values(p_origin_hash,p_mode,false,'unavailable');return null;end if;
 if v_profile.visibility@>'{"contacts":true}'::jsonb then select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('name',c.name,'relationship',c.relationship,'phone',c.phone))order by c.sort_order,c.created_at),'[]'::jsonb)into v_contacts from public.emergency_contacts c where c.emergency_profile_id=v_profile.id and c.user_id=v_profile.user_id and c.is_public=true;else v_contacts:='[]'::jsonb;end if;
 v_result:=jsonb_strip_nulls(jsonb_build_object('preferredName',case when v_profile.visibility@>'{"preferred_name":true}'::jsonb then v_profile.preferred_name end,'age',case when v_profile.visibility@>'{"age":true}'::jsonb and v_profile.birth_date is not null then date_part('year',age(current_date,v_profile.birth_date))::int end,'pronouns',case when v_profile.visibility@>'{"pronouns":true}'::jsonb then v_profile.pronouns end,'bloodType',case when v_profile.visibility@>'{"blood_type":true}'::jsonb then v_profile.blood_type end,'allergies',case when v_profile.visibility@>'{"allergies":true}'::jsonb then v_profile.allergies end,'conditions',case when v_profile.visibility@>'{"conditions":true}'::jsonb then v_profile.conditions end,'medications',case when v_profile.visibility@>'{"medications":true}'::jsonb then v_profile.medications end,'supportNeeds',case when v_profile.visibility@>'{"support_needs":true}'::jsonb then v_profile.support_needs end,'medicalDevices',case when v_profile.visibility@>'{"medical_devices":true}'::jsonb then v_profile.medical_devices end,'healthPlanName',case when v_profile.visibility@>'{"health_plan_name":true}'::jsonb then v_profile.health_plan_name end,'otherGuidance',case when v_profile.visibility@>'{"other_guidance":true}'::jsonb then v_profile.other_guidance end,'contacts',v_contacts,'updatedAt',v_profile.updated_at));
 insert into private.emergency_lookup_attempts(origin_hash,lookup_mode,succeeded,outcome)values(p_origin_hash,p_mode,true,'found');return v_result;
end$$;
revoke all on function public.server_get_emergency_profile(text,bytea,bytea,text,boolean)from public,anon,authenticated;
grant execute on function public.server_get_emergency_profile(text,bytea,bytea,text,boolean)to service_role;
