"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";
const CODE_PATTERN=/^[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{5}$/;
type ProfileOption={id:string;preferred_name:string|null;subject_relationship:"self"|"child"|"dependent"};
export default function AtivarClient({profiles}:{profiles:ProfileOption[]}){
 const[done,setDone]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 async function activate(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=event.currentTarget;const data=new FormData(form);const profileId=String(data.get("profileId")??"");const publicCode=String(data.get("publicCode")??"").trim().toUpperCase();const activationSecret=String(data.get("activationSecret")??"");if(!profiles.some(item=>item.id===profileId)||!CODE_PATTERN.test(publicCode)||activationSecret.length<12||activationSecret.length>256){setError("Escolha um perfil e confira os códigos do produto.");return}setLoading(true);const{error:invokeError}=await createClient().functions.invoke("activate-product",{body:{profileId,publicCode,activationSecret}});setLoading(false);const secretInput=form.elements.namedItem("activationSecret")as HTMLInputElement|null;if(secretInput)secretInput.value="";if(invokeError){setError("Não foi possível ativar o produto. Confira os códigos e tente novamente.");return}setDone(true)}
 return <main className="appShell"><Link className="brand" href="/"><b>R</b>Resolveu<span>Lab</span></Link><section className="formCard"><p className="kicker">ATIVAÇÃO SEGURA</p><h1>{done?"Resolveu SOS ativado!":"Vamos vincular seu chaveiro"}</h1>{done?<><p>O produto foi vinculado ao perfil escolhido. O perfil continua privado até a publicação.</p><Link className="primary linkButton" href="/painel">Configurar o perfil →</Link></>:profiles.length===0?<><p>Crie primeiro o perfil da pessoa que usará este chaveiro. Pode ser você, um filho ou outro dependente.</p><Link className="primary linkButton" href="/painel">Criar perfil →</Link></>:<form onSubmit={activate}><label>Perfil que usará o chaveiro<select name="profileId" required defaultValue=""><option value="" disabled>Selecione um perfil</option>{profiles.map(profile=><option value={profile.id} key={profile.id}>{profile.preferred_name||"Sem nome"} — {profile.subject_relationship==="self"?"meu perfil":profile.subject_relationship==="child"?"filho(a)":"dependente"}</option>)}</select></label><label>Código público<input name="publicCode" required pattern="[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{5}" maxLength={5} autoCapitalize="characters" autoComplete="off" placeholder="7KM4Q" disabled={loading}/></label><label>Código secreto de ativação<input name="activationSecret" required minLength={12} maxLength={256} type="password" autoComplete="one-time-code" placeholder="••••••••••••" disabled={loading}/></label><label className="check"><input required type="checkbox" disabled={loading}/> Confirmo que sou responsável por este produto e pelo perfil selecionado.</label>{error&&<p className="formError" role="alert">{error}</p>}<button className="primary" disabled={loading}>{loading?"Ativando…":"Ativar com segurança →"}</button><small>O código secreto é usado somente nesta ativação e não fica disponível depois.</small></form>}</section></main>}
